### ISSUE TITLE
Batch processing leaves files without Dimensions/Audio-Video Track properties

### ISSUE THREAD

**Issue by loungebob** [BrunoReX/jmkvpropedit#12]
Using 1.4.3 to process folders containing mkv files.

Unfortunately I chose a rather large test folder and even though I’m pretty sure I configured everything properly to name all
tracks based on the file names and the batch job seems to have run just fine, the result shows about 90% of the files now without dimensions info in Windows File Explorer and no track information whatsoever in Mediainfo.

The header editor shows all properties present in the file for those files missing the information in File Explorer and Mediainfo but they dont display/show.

The only way to get them back is to remux the files with mkvmerge which makes them show all metadata properly again.

What am I doing wrong? 

The only difference between the files showing the data properly and the large number of files not displaying any info at all seems to be the writing library. 
mkvmerge processed files with ibebml v1.3.5 + libmatroska v1.4.8 / Lavf57.7.2

**Comment by Wakakug** [comment]
Hello. Probably an issue with the CLI "mkvpropedit.exe" (and MKVToolNix GUI as well) instead of JMkvpropedit itself (since JMkvpropedit uses or relies on that external CLI). We have somewhat a little bit similar experiences.

In my experience after I successfully embedded XML tags and cover.jpg into an MKV, and then sometime later edit the header tags using MKVToolNix GUI's header editor (or sometimes JMkvpropedit), almost 90% of the time that my earlier embedded XML tags and cover.jpg are no longer displayed in MediaInfo, and the Writing Library and Writing Application are the ones mainly left.

But in reality my earlier embedded XML tags and cover.jpg are really there, so just like you I have to remux using MKVToolNix in order for those to appear again in MediaInfo. Similar case with Avidemux, where I must remux, because if I do not, Avidemux seems to have some seeking issues (seekbar) while editing. After remuxing, seeking is easier and more fluid.

So if indeed we have somewhat similar situations, then you have not done anything wrong. You just have to remux again just like me especially after you re-edited those header tags. In fact I ended up creating my own BATCH file (.bat) to remux my multiple MKVs again conveniently. If you intend to use mkvpropedit.exe/JMkvpropedit/MKVToolNix GUI, then perhaps you might want to create your own batch file as well.
